2025-07-14 16:21:39,337 INFO    MainThread:508587 [wandb_setup.py:_flush():80] Current SDK version is 0.21.0
2025-07-14 16:21:39,337 INFO    MainThread:508587 [wandb_setup.py:_flush():80] Configure stats pid to 508587
2025-07-14 16:21:39,337 INFO    MainThread:508587 [wandb_setup.py:_flush():80] Loading settings from /gpfs/radev/home/jh3439/.config/wandb/settings
2025-07-14 16:21:39,337 INFO    MainThread:508587 [wandb_setup.py:_flush():80] Loading settings from /gpfs/radev/project/zhuoran_yang/jh3439/simple-post-training/wandb/settings
2025-07-14 16:21:39,337 INFO    MainThread:508587 [wandb_setup.py:_flush():80] Loading settings from environment variables
2025-07-14 16:21:39,337 INFO    MainThread:508587 [wandb_init.py:setup_run_log_directory():703] Logging user logs to /gpfs/radev/project/zhuoran_yang/jh3439/simple-post-training/wandb/run-20250714_162139-5cqnykkk/logs/debug.log
2025-07-14 16:21:39,338 INFO    MainThread:508587 [wandb_init.py:setup_run_log_directory():704] Logging internal logs to /gpfs/radev/project/zhuoran_yang/jh3439/simple-post-training/wandb/run-20250714_162139-5cqnykkk/logs/debug-internal.log
2025-07-14 16:21:39,338 INFO    MainThread:508587 [wandb_init.py:init():830] calling init triggers
2025-07-14 16:21:39,338 INFO    MainThread:508587 [wandb_init.py:init():835] wandb.init called with sweep_config: {}
config: {'_wandb': {}}
2025-07-14 16:21:39,338 INFO    MainThread:508587 [wandb_init.py:init():871] starting backend
2025-07-14 16:21:39,784 INFO    MainThread:508587 [wandb_init.py:init():874] sending inform_init request
2025-07-14 16:21:39,787 INFO    MainThread:508587 [wandb_init.py:init():882] backend started and connected
2025-07-14 16:21:39,788 INFO    MainThread:508587 [wandb_init.py:init():953] updated telemetry
2025-07-14 16:21:39,803 INFO    MainThread:508587 [wandb_init.py:init():977] communicating run to backend with 90.0 second timeout
2025-07-14 16:21:40,345 INFO    MainThread:508587 [wandb_init.py:init():1029] starting run threads in backend
2025-07-14 16:21:42,077 INFO    MainThread:508587 [wandb_run.py:_console_start():2458] atexit reg
2025-07-14 16:21:42,077 INFO    MainThread:508587 [wandb_run.py:_redirect():2306] redirect: wrap_raw
2025-07-14 16:21:42,077 INFO    MainThread:508587 [wandb_run.py:_redirect():2375] Wrapping output streams.
2025-07-14 16:21:42,077 INFO    MainThread:508587 [wandb_run.py:_redirect():2398] Redirects installed.
2025-07-14 16:21:42,079 INFO    MainThread:508587 [wandb_init.py:init():1075] run started, returning control to user process
2025-07-14 16:23:28,239 INFO    MsgRouterThr:508587 [mailbox.py:close():129] [no run ID] Closing mailbox, abandoning 1 handles.
2025-07-14 16:23:29,180 INFO    MainThread:508587 [wandb_run.py:_finish():2224] finishing run jlianghe-yale-university/verl-post-training-pipeline-sft/5cqnykkk
2025-07-14 16:23:29,180 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,220 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,220 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,220 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,221 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,304 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,305 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,305 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,305 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,306 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,306 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,306 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,307 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,307 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,307 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,307 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,308 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,308 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,308 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,308 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,309 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,309 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,309 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,309 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,310 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,310 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,311 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,311 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,311 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,312 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,312 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,312 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,312 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,313 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,313 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,313 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,313 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,314 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,314 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,314 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,314 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,315 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,315 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,315 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,315 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,316 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,316 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,316 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,316 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,317 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,317 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,317 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,317 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,318 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,318 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,318 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,318 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,319 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,319 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,320 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,320 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,320 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,320 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,320 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,321 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,321 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,321 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,321 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,321 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,322 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,322 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
2025-07-14 16:23:29,322 ERROR   MainThread:508587 [redirect.py:_on_write():664] [all runs] error in stderr callback
Traceback (most recent call last):
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/redirect.py", line 662, in _on_write
    cb(written_data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 2385, in <lambda>
    lambda data: self._console_raw_callback("stderr", data),
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 398, in wrapper
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 456, in wrapper_fn
    return func(self, *args, **kwargs)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/wandb_run.py", line 1566, in _console_raw_callback
    self._backend.interface.publish_output_raw(name, data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface.py", line 771, in publish_output_raw
    self._publish_output_raw(o)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_shared.py", line 38, in _publish_output_raw
    self._publish(rec)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/interface/interface_sock.py", line 39, in _publish
    self._sock_client.send_record_publish(record)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 170, in send_record_publish
    self.send_server_request(server_req)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 150, in send_server_request
    self._send_message(msg)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 147, in _send_message
    self._sendall_with_error_handle(header + data)
  File "/gpfs/radev/home/jh3439/.conda/envs/llm_base/lib/python3.10/site-packages/wandb/sdk/lib/sock_client.py", line 126, in _sendall_with_error_handle
    sent = self._sock.send(data)
BrokenPipeError: [Errno 32] Broken pipe
